/*
This file defines the visual layout of the Market Basket store/floorplan.

Each object represents a section of the store:
- code: matches the inventory data
- label: what is displayed on the map
- x, y: position on the map
- width, height: size of the section
- color: visual styling
*/
import { StoreSection } from  "./types";

export const marketBasketSections: StoreSection[] = [
    {
        id: "produce",
        label: "Produce",
        code: "PROD",
        x: 40,
        y: 60,
        width: 170,
        height: 90,
        color: "#bbf7d0",
    },
    {
        id: "bakery",
        label: "Bakery",
        code: "BAKE",
        x: 240,
        y: 60,
        width: 140,
        height: 90,
        color: "#fde68a",
    },
    {
        id: "deli",
        label: "Deli",
        code: "DELI",
        x: 410,
        y: 60,
        width: 140,
        height: 90,
        color: "#fecaca",
    },
    {
        id: "meat",
        label: "Meat",
        code: "MEAT",
        x: 580,
        y: 60,
        width: 140,
        height: 90,
        color: "#fca5a5",
    },
    {
        id: "frozen",
        label: "Frozen",
        code: "FROZ",
        x: 760,
        y: 60,
        width: 170,
        height: 90,
        color: "#bfdbfe",
    },
    {
        id: "dairy",
        label: "Dairy",
        code: "DAIRY",
        x: 760,
        y: 180,
        width: 170,
        height: 90,
        color: "#c7d2fe",
    },
    {
        id: "aisle-1",
        label: "Aisle 1",
        code: "A1",
        x: 140,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "aisle-2",
        label: "Aisle 2",
        code: "A2",
        x: 250,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "aisle-3",
        label: "Aisle 3",
        code: "A3",
        x: 360,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "aisle-4",
        label: "Aisle 4",
        code: "A4",
        x: 470,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "aisle-5",
        label: "Aisle 5",
        code: "A5",
        x: 580,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "aisle-6",
        label: "Aisle 6",
        code: "A6",
        x: 690,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "aisle-15",
        label: "Aisle 15",
        code: "A15",
        x: 800,
        y: 210,
        width: 90,
        height: 220,
        color: "#f3f4f6",
    },
    {
        id: "checkout",
        label: "Checkout",
        code: "REG",
        x: 650,
        y: 480,
        width: 250,
        height: 70,
        color: "#d1d5db",
    },
];